version: '3.8'

services:
  application:
    image: glitchguy0/js-api:latest
    container_name: application
    restart: 'no'
    # ports:
    #   - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: 'no'
    # ports:
    #   - "27017:27017"

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "3000:5000" #  <= application entry point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: 'no'
    depends_on:
      - application